/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./src/components/Article/Anchor.vue')['default']
    ArticleDetails: typeof import('./src/components/Article/ArticleDetails.vue')['default']
    ArticleModule: typeof import('./src/components/Article/ArticleModule.vue')['default']
    ArticleRightModule: typeof import('./src/components/Article/ArticleRightModule.vue')['default']
    ArticleSkeleton: typeof import('./src/components/Article/ArticleSkeleton.vue')['default']
    BackgroundPlate: typeof import('./src/components/background/BackgroundPlate.vue')['default']
    BlogManagement: typeof import('./src/components/PersonalCenter/InfoCard/BlogManagement.vue')['default']
    CommentJs: typeof import('./src/components/comment/comment-js.vue')['default']
    DiaryModule: typeof import('./src/components/Diary/DiaryModule.vue')['default']
    GuestbookJs: typeof import('./src/components/Guestbook/guestbook-js.vue')['default']
    InfoCard: typeof import('./src/components/PersonalCenter/InfoCard.vue')['default']
    LinkCard: typeof import('./src/components/MyLinks/LinkCard.vue')['default']
    LinkCardBox: typeof import('./src/components/FriendLink/LinkCardBox.vue')['default']
    LoginCard: typeof import('./src/components/Login/LoginCard.vue')['default']
    MdEditorComponent: typeof import('./src/components/MdEditor/MdEditorComponent.vue')['default']
    MyArticle: typeof import('./src/components/PersonalCenter/InfoCard/MyArticle.vue')['default']
    MyClassify: typeof import('./src/components/PersonalCenter/InfoCard/MyClassify.vue')['default']
    MyComment: typeof import('./src/components/PersonalCenter/InfoCard/MyComment.vue')['default']
    MyDiarys: typeof import('./src/components/PersonalCenter/InfoCard/MyDiarys.vue')['default']
    MyGuestBook: typeof import('./src/components/PersonalCenter/InfoCard/MyGuestBook.vue')['default']
    MyImg: typeof import('./src/components/Article/myImg.vue')['default']
    MyInformation: typeof import('./src/components/PersonalCenter/InfoCard/MyInformation.vue')['default']
    MyLabel: typeof import('./src/components/PersonalCenter/InfoCard/MyLabel.vue')['default']
    MyLinks: typeof import('./src/components/PersonalCenter/InfoCard/MyLinks.vue')['default']
    MyPayment: typeof import('./src/components/PersonalCenter/InfoCard/MyPayment.vue')['default']
    MyUsers: typeof import('./src/components/PersonalCenter/InfoCard/MyUsers.vue')['default']
    PersonalProfile: typeof import('./src/components/Article/PersonalProfile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}
